### ISSUE TITLE
host on springrts.com

### ISSUE THREAD

**Issue by abma** [TurBoss/Glenda#1]
can we host this on springrts.com?

**Comment by TurBoss** [comment]
sure give me some time please

**Comment by TurBoss** [comment]
I'm planning to implement this : https://github.com/matrix-org/matrix-appservice-irc a transparen irc bridge,

users don't talk behind a bot eg. ```"<BridgeBot><Nick> Hello"``` they login directly to the irc server

Question: Could be posible to allow multiple logins? this way a user can be connected from a lobby and from the bridge at the same time

Thanks

**Comment by abma** [comment]
> Question: Could be posible to allow multiple logins? this way a user can be connected from a lobby and from the bridge at the same time

short answer: no.
long answer: the protocol isn't made to support the same user beeing logged in multiple times. at least some changes are needed, not sure how to implement it ideally. without much thinking i would add a prefix or suffix to the username when logging in via a bridge. i.e. "abma" becomes abma#matrix or abma#irc. this requires some small changes to uberserver but should be compatible to existing lobby clients.

**Comment by TurBoss** [comment]
thanks , no worries I'll take a look when arraive home

**Comment by TurBoss** [comment]
done
